defmodule NexusAvatars.Generator do
  @moduledoc """
  Core avatar generation pipeline.

  For a given user and style, this module:
    1. Builds an SVG string via the appropriate style module
    2. Rasterizes it to a 256x256 WebP via libvips (Image library)
    3. Stores the file under nexus-avatars/avatars/nxa_{hex}.webp
    4. Updates users.avatar_url via Nexus.Accounts.update_avatar/2
    5. Upserts the style choice into nexus_avatars_user_styles

  All generated filenames are prefixed with `nxa_` so the flush operation
  can identify and remove only files produced by this extension.
  """

  require Logger

  import Ecto.Query

  alias Nexus.Repo
  alias Nexus.Accounts
  alias NexusAvatars.UserStyle

  @slug        "nexus-avatars"
  @size        256
  @all_styles  NexusAvatars.UserStyle.valid_styles()

  # ---------------------------------------------------------------------------
  # Public API
  # ---------------------------------------------------------------------------

  @doc """
  Generates and persists an avatar for the given user in the given style.
  Returns {:ok, public_url} or {:error, reason}.
  """
  def generate_for_user(user, style) when style in @all_styles do
    with {:ok, svg}     <- build_svg(user.username, style),
         {:ok, webp}    <- rasterize(svg),
         {:ok, rel_url} <- store(webp, user.username),
         {:ok, _user}   <- Accounts.update_avatar(user, rel_url),
         :ok            <- upsert_style(user.id, style) do
      {:ok, rel_url}
    end
  end

  def generate_for_user(_user, style) do
    {:error, "Unknown style: #{style}"}
  end

  @doc """
  Picks a style for the given username based on current settings.

  If random is true, picks randomly from the enabled pool.
  If random is false, picks deterministically via username hash (same user
  always gets the same style from the pool).
  If the enabled pool is empty, returns nil and no avatar is generated.
  """
  def pick_style(username, settings) do
    pool   = enabled_pool(settings)
    random = Map.get(settings, "random", true)

    case pool do
      [] ->
        nil

      styles ->
        if random do
          Enum.random(styles)
        else
          index = :erlang.phash2(username, length(styles))
          Enum.at(styles, index)
        end
    end
  end

  @doc """
  Returns the list of enabled styles from settings.
  Falls back to all styles if the setting is missing or empty.
  """
  def enabled_pool(settings) do
    raw = Map.get(settings, "enabled_styles", "")

    styles =
      raw
      |> String.split(",", trim: true)
      |> Enum.map(&String.trim/1)
      |> Enum.filter(&(&1 in @all_styles))

    if styles == [], do: @all_styles, else: styles
  end

  @doc """
  Returns the style stored for a user, or nil if none.
  """
  def get_user_style(user_id) do
    case Repo.get_by(UserStyle, user_id: user_id) do
      nil    -> nil
      record -> record.style
    end
  end

  @doc """
  Counts users who currently have no avatar_url set.
  Used by the admin panel to show the pending count.
  """
  def count_users_without_avatar do
    Repo.aggregate(
      from(u in Nexus.Accounts.User, where: is_nil(u.avatar_url)),
      :count
    )
  end

  @doc """
  Counts users who have an nxa_ avatar (generated by this extension).
  Used by the admin flush panel.
  """
  def count_generated_avatars do
    Repo.aggregate(
      from(u in Nexus.Accounts.User,
        where: not is_nil(u.avatar_url) and like(u.avatar_url, "nxa_%")),
      :count
    )
  end

  @doc """
  Deletes all nxa_ avatars from storage and clears them from user records.
  Returns %{users_cleared: n, files_deleted: n}.
  """
  def flush_all do
    # Collect filenames before clearing DB records
    nxa_filenames =
      from(u in Nexus.Accounts.User,
        where: not is_nil(u.avatar_url) and like(u.avatar_url, "nxa_%"),
        select: u.avatar_url)
      |> Repo.all()

    # Clear avatar_url for all nxa_ users
    {users_cleared, _} =
      from(u in Nexus.Accounts.User,
        where: not is_nil(u.avatar_url) and like(u.avatar_url, "nxa_%"))
      |> Repo.update_all(set: [avatar_url: nil])

    # Delete all style records
    Repo.delete_all(UserStyle)

    # Delete files from storage
    files_deleted =
      nxa_filenames
      |> Enum.reduce(0, fn url, acc ->
        # url is like "nxa_abc123.webp" — strip leading slash if present
        filename = Path.basename(url)
        path     = Nexus.Extensions.Storage.path(@slug, "avatars/#{filename}")

        case File.rm(path) do
          :ok              -> acc + 1
          {:error, reason} ->
            Logger.warning("NexusAvatars: flush could not delete #{filename}: #{inspect(reason)}")
            acc
        end
      end)

    # Sweep for any orphaned nxa_ files not in the DB
    avatar_dir = Nexus.Extensions.Storage.path(@slug, "avatars")
    orphan_count =
      case File.ls(avatar_dir) do
        {:ok, files} ->
          files
          |> Enum.filter(&String.starts_with?(&1, "nxa_"))
          |> Enum.reduce(0, fn filename, acc ->
            path = Path.join(avatar_dir, filename)
            case File.rm(path) do
              :ok -> acc + 1
              _   -> acc
            end
          end)

        {:error, _} ->
          0
      end

    %{users_cleared: users_cleared, files_deleted: files_deleted + orphan_count}
  end

  # ---------------------------------------------------------------------------
  # Private — SVG dispatch
  # ---------------------------------------------------------------------------

  defp build_svg(username, "mech"),     do: {:ok, NexusAvatars.Generator.Mech.render(username)}
  defp build_svg(username, "feline"),   do: {:ok, NexusAvatars.Generator.Feline.render(username)}
  defp build_svg(username, "canine"),   do: {:ok, NexusAvatars.Generator.Canine.render(username)}
  defp build_svg(username, "inkblot"),  do: {:ok, NexusAvatars.Generator.Inkblot.render(username)}
  defp build_svg(username, "emblem"),   do: {:ok, NexusAvatars.Generator.Emblem.render(username)}
  defp build_svg(username, "snowflake"), do: {:ok, NexusAvatars.Generator.Snowflake.render(username)}
  defp build_svg(_username, style),     do: {:error, "No renderer for style: #{style}"}

  # ---------------------------------------------------------------------------
  # Private — rasterization via libvips
  # ---------------------------------------------------------------------------

  defp rasterize(svg_string) do
    try do
      image =
        svg_string
        |> then(&Image.from_svg!(&1, width: @size))

      webp_binary = Image.write_to_binary!(image, ".webp", quality: 85)
      {:ok, webp_binary}
    rescue
      e -> {:error, "Rasterization failed: #{inspect(e)}"}
    end
  end

  # ---------------------------------------------------------------------------
  # Private — storage
  # ---------------------------------------------------------------------------

  defp store(webp_binary, username) do
    :ok = Nexus.Extensions.Storage.ensure_dir(@slug, "avatars")

    # nxa_ prefix + username hash for uniqueness and flush identification
    hex      = :crypto.strong_rand_bytes(12) |> Base.encode16(case: :lower)
    filename = "nxa_#{:erlang.phash2(username)}_#{hex}.webp"
    path     = Nexus.Extensions.Storage.path(@slug, "avatars/#{filename}")

    case File.write(path, webp_binary) do
      :ok ->
        # Return just the filename — update_avatar stores this in avatar_url.
        # Nexus serves it via /uploads/extensions/nexus-avatars/avatars/{filename}
        # but we store only the filename so the nxa_ prefix check works.
        {:ok, "nxa_#{:erlang.phash2(username)}_#{hex}.webp"}

      {:error, reason} ->
        {:error, "Storage write failed: #{inspect(reason)}"}
    end
  end

  # ---------------------------------------------------------------------------
  # Private — style persistence
  # ---------------------------------------------------------------------------

  defp upsert_style(user_id, style) do
    case Repo.get_by(UserStyle, user_id: user_id) do
      nil ->
        %UserStyle{}
        |> UserStyle.changeset(%{user_id: user_id, style: style})
        |> Repo.insert()

      existing ->
        existing
        |> UserStyle.changeset(%{style: style})
        |> Repo.update()
    end
    |> case do
      {:ok, _}    -> :ok
      {:error, e} -> {:error, e}
    end
  end
end
