defmodule NexusAvatars.Generator.Inkblot do
  @moduledoc """
  Inkblot avatar style.

  Renders a 200x200 symmetric inkblot on a flat background.
  The inkblot is generated by:

    1. Placing points in polar space clustered into random lobes,
       with deep angular gaps between them — this creates concave
       bays and distinct lobes rather than smooth blobs.
    2. Mirroring the left-side polygon exactly across x=100
       to produce perfect bilateral symmetry.
    3. Adding separate sub-lobe blobs near the main shape edges.
    4. Adding thin kinked tendrils radiating outward.
    5. Adding scattered splatter dots, all mirrored.

  No SVG filters — pure polygon/circle geometry, fully librsvg-safe.

  Canvas: 200x200, viewBox 0 0 200 200. Rasterised to WebP via libvips.
  """

  @size 200

  @palettes [
    {"#f4f0e8", "#12100c"}, {"#f8f4ec", "#0c0a08"}, {"#eeeae0", "#181410"},
    {"#faf6ee", "#08060a"}, {"#f0ece0", "#200808"},
    {"#0c0a08", "#f0ead8"}, {"#08080e", "#d8e8f8"}, {"#060e06", "#c8f0b0"},
    {"#0a0608", "#e82840"}, {"#060810", "#2090ff"}, {"#080608", "#c040f0"},
    {"#060804", "#f09020"}, {"#040a0a", "#10c8b8"}, {"#0e0608", "#ff80a0"},
    {"#180804", "#ffd060"}, {"#0c1018", "#80c8ff"}, {"#100418", "#e090ff"},
    {"#0e1408", "#90e040"}, {"#100808", "#ff6040"}, {"#08100e", "#40e8a0"},
    {"#100c18", "#f0c0ff"}, {"#180c04", "#ffb060"}, {"#040c10", "#60f0e0"},
    {"#0c0818", "#ff60b0"}, {"#181008", "#c0ff80"}, {"#08180c", "#80a0ff"},
  ]

  @shape_types [{72,50},{52,72},{60,60},{76,48},{46,72}]

  # ── Public entry point ───────────────────────────────────────────

  @doc "Renders a 200x200 Inkblot SVG string for the given username."
  def render(username) do
    seed = :erlang.phash2(username)
    {bg, ink} = Enum.at(@palettes, rem(seed, length(@palettes)))

    {left_pts, right_pts, cx, cy, rx, ry} = generate_blot(seed)

    [
      ~s(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 #{@size} #{@size}" width="#{@size}" height="#{@size}">),
      ~s(<rect width="#{@size}" height="#{@size}" fill="#{bg}"/>),
      generate_sub_lobes(seed, ink, cx, cy, rx, ry),
      poly_svg(left_pts,  ink),
      poly_svg(right_pts, ink),
      generate_tendrils(seed, ink, cx, cy, rx, ry),
      generate_dots(seed, ink),
      "</svg>",
    ]
    |> Enum.join("")
  end

  # ── PRNG: splitmix32 ─────────────────────────────────────────────

  defp sm_init(seed, salt) do
    Bitwise.band(Bitwise.bxor(seed, salt * 0x9e3779b9), 0xFFFFFFFF)
  end

  defp sm_next(s) do
    s1 = Bitwise.band(s + 0x9e3779b9, 0xFFFFFFFF)
    z  = s1
    z  = Bitwise.band(Bitwise.bxor(z, Bitwise.bsr(z, 16)) * 0x85ebca6b, 0xFFFFFFFF)
    z  = Bitwise.band(Bitwise.bxor(z, Bitwise.bsr(z, 13)) * 0xc2b2ae35, 0xFFFFFFFF)
    z  = Bitwise.band(Bitwise.bxor(z, Bitwise.bsr(z, 16)), 0xFFFFFFFF)
    {z / 0x100000000, s1}
  end

  defp sm_warmup(s) do
    {_, s1} = sm_next(s)
    {_, s2} = sm_next(s1)
    s2
  end

  # ── Main blot ────────────────────────────────────────────────────

  defp generate_blot(seed) do
    s0 = sm_warmup(sm_init(seed, 1))

    {sv, s1}  = sm_next(s0)
    {rx, ry}  = Enum.at(@shape_types, ifloor(sv * 5))
    cx = 100; cy = 100

    {lv, s2} = sm_next(s1)
    num_lobes = 2 + ifloor(lv * 4)

    {lobe_angles, s3} =
      Enum.reduce(1..num_lobes, {[], s2}, fn _, {acc, st} ->
        {v, st2} = sm_next(st)
        {[v * :math.pi() | acc], st2}
      end)
    lobe_angles = Enum.sort(lobe_angles)

    pi = :math.pi()

    {atv, s4}  = sm_next(s3)
    {arv, s5}  = sm_next(s4)
    {abv, s6}  = sm_next(s5)
    {abrv, s7} = sm_next(s6)

    anchor_top = {-0.05 + atv * 0.1,    8.0 + arv  * 20.0}
    anchor_bot = {pi - 0.05 + abv * 0.1, 8.0 + abrv * 20.0}

    {lobe_pts, _s_end} =
      Enum.reduce(lobe_angles, {[], s7}, fn base_a, {pts_acc, st} ->
        {lw_v, st1} = sm_next(st)
        {ls_v, st2} = sm_next(st1)
        {pc_v, st3} = sm_next(st2)
        lobe_width = 0.3 + lw_v * 0.4
        lobe_size  = 0.5 + ls_v * 0.5
        pt_count   = 4 + ifloor(pc_v * 6)

        {new_pts, st_out} =
          Enum.reduce(1..pt_count, {[], st3}, fn _, {pacc, pst} ->
            {av, pst1} = sm_next(pst)
            {rv, pst2} = sm_next(pst1)
            a = base_a + (av - 0.5) * lobe_width * 2
            if a < -0.1 or a > pi + 0.1 do
              {pacc, pst2}
            else
              dist     = 1.0 - abs(a - base_a) / (lobe_width * 1.5)
              r_dist   = 0.4 + dist * 0.6 * lobe_size
              base_rad = (rx * abs(:math.cos(a)) + ry * abs(:math.sin(a))) * 0.5
              final_r  = base_rad * r_dist * (0.85 + rv * 0.3)
              {[{a, final_r} | pacc], pst2}
            end
          end)

        {new_pts ++ pts_acc, st_out}
      end)

    all_pts = [anchor_top, anchor_bot | lobe_pts]
    sorted  = Enum.sort_by(all_pts, fn {a, _} -> a end)

    ry_scale = ry / max(rx, ry)
    left_pts = Enum.map(sorted, fn {a, r} ->
      x = rclamp(cx - r * :math.sin(a), 0, 100)
      y = rclamp(cy - r * :math.cos(a) * ry_scale, 4, 196)
      {x, y}
    end)
    right_pts = Enum.map(left_pts, fn {x, y} -> {200 - x, y} end)

    {left_pts, right_pts, cx, cy, rx, ry}
  end

  # ── Sub-lobes ────────────────────────────────────────────────────

  defp generate_sub_lobes(seed, ink, cx, cy, rx, ry) do
    s0 = sm_warmup(sm_init(seed, 2))
    {cv, s1} = sm_next(s0)
    count = 1 + ifloor(cv * 4)

    {parts, _} =
      Enum.reduce(1..count, {[], s1}, fn _, {acc, st} ->
        {av,  st1} = sm_next(st)
        {dv,  st2} = sm_next(st1)
        {brv, st3} = sm_next(st2)
        {npv, st4} = sm_next(st3)

        a    = av * :math.pi()
        dist = 0.7 + dv * 0.4
        bx   = rclamp(cx - rx * dist * :math.sin(a), 0, 100)
        byt  = rclamp(cy - ry * 0.8 * :math.cos(a), 4, 196)
        brad = 4 + ifloor(brv * 18)
        npts = 5 + ifloor(npv * 5)

        {sub_pts, st_out} =
          Enum.reduce(0..(npts - 1), {[], st4}, fn j, {pacc, pst} ->
            {rv, pst2} = sm_next(pst)
            pa = j / npts * :math.pi() * 2
            pr = brad * (0.6 + rv * 0.7)
            px = rclamp(bx  + pr * :math.cos(pa), 0, 100)
            py = rclamp(byt + pr * :math.sin(pa), 4, 196)
            {[{px, py} | pacc], pst2}
          end)

        r_pts  = Enum.map(sub_pts, fn {x, y} -> {200 - x, y} end)
        svg    = poly_svg(sub_pts, ink) <> poly_svg(r_pts, ink)
        {[svg | acc], st_out}
      end)

    Enum.join(parts, "")
  end

  # ── Tendrils ─────────────────────────────────────────────────────

  defp generate_tendrils(seed, ink, cx, cy, rx, ry) do
    s0 = sm_warmup(sm_init(seed, 3))
    {cv, s1} = sm_next(s0)
    count = 1 + ifloor(cv * 5)

    {parts, _} =
      Enum.reduce(1..count, {[], s1}, fn _, {acc, st} ->
        {av,   st1} = sm_next(st)
        {lenv, st2} = sm_next(st1)
        {widv, st3} = sm_next(st2)
        {kv,   st4} = sm_next(st3)

        a     = av * :math.pi()
        bx    = rf(cx - rx * 0.85 * :math.sin(a))
        byt   = rf(cy - ry * 0.75 * :math.cos(a))
        len   = 10.0 + lenv * 30.0
        wid   = 2.0  + widv * 5.0
        out_a = :math.atan2(byt - cy, bx - cx)
        kink_a = out_a + (kv - 0.5) * 0.6

        tx   = rf(bx  + len * :math.cos(out_a))
        ty   = rf(byt + len * :math.sin(out_a))
        kx   = rf(bx  + len * 0.5 * :math.cos(kink_a))
        ky   = rf(byt + len * 0.5 * :math.sin(kink_a))

        perp = out_a + :math.pi() / 2
        p1x  = rf(bx  + wid * :math.cos(perp))
        p1y  = rf(byt + wid * :math.sin(perp))
        p2x  = rf(bx  - wid * :math.cos(perp))
        p2y  = rf(byt - wid * :math.sin(perp))

        l_pts = [{p1x,p1y},{kx,ky},{tx,ty},{kx,ky},{p2x,p2y}]
        r_pts = Enum.map(l_pts, fn {x, y} -> {200 - x, y} end)
        svg   = poly_svg(l_pts, ink) <> poly_svg(r_pts, ink)
        {[svg | acc], st4}
      end)

    Enum.join(parts, "")
  end

  # ── Splatter dots ────────────────────────────────────────────────

  defp generate_dots(seed, ink) do
    s0 = sm_warmup(sm_init(seed, 4))
    {cv, s1} = sm_next(s0)
    count = 4 + ifloor(cv * 10)

    {parts, _} =
      Enum.reduce(1..count, {[], s1}, fn _, {acc, st} ->
        {xv, st1} = sm_next(st)
        {yv, st2} = sm_next(st1)
        {rv, st3} = sm_next(st2)
        x = round(10 + xv * 85)
        y = round(10 + yv * 180)
        r = 1 + ifloor(rv * 5)
        svg = ~s(<circle cx="#{x}" cy="#{y}" r="#{r}" fill="#{ink}"/>) <>
              ~s(<circle cx="#{200 - x}" cy="#{y}" r="#{r}" fill="#{ink}"/>)
        {[svg | acc], st3}
      end)

    Enum.join(parts, "")
  end

  # ── Helpers ──────────────────────────────────────────────────────

  defp poly_svg(pts, fill) do
    pt_str = Enum.map_join(pts, " ", fn {x, y} -> "#{x},#{y}" end)
    ~s(<polygon points="#{pt_str}" fill="#{fill}"/>)
  end

  defp rclamp(v, lo, hi), do: max(lo, min(hi, round(v)))
  defp rf(v), do: round(v)
  defp ifloor(v), do: trunc(:math.floor(v))
end
